//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRealTimeUnit")]
    public interface IRealTimeUnit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/initialize", ReplyAction="http://tempuri.org/IRealTimeUnit/initializeResponse")]
        bool initialize(string id, string io, double lowLimit, double highLimit, byte[] signature, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/initialize", ReplyAction="http://tempuri.org/IRealTimeUnit/initializeResponse")]
        System.Threading.Tasks.Task<bool> initializeAsync(string id, string io, double lowLimit, double highLimit, byte[] signature, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/ValueToAddres", ReplyAction="http://tempuri.org/IRealTimeUnit/ValueToAddresResponse")]
        void ValueToAddres(string io, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/ValueToAddres", ReplyAction="http://tempuri.org/IRealTimeUnit/ValueToAddresResponse")]
        System.Threading.Tasks.Task ValueToAddresAsync(string io, int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitChannel : RealTimeUnit.ServiceReference1.IRealTimeUnit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference1.IRealTimeUnit>, RealTimeUnit.ServiceReference1.IRealTimeUnit {
        
        public RealTimeUnitClient() {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool initialize(string id, string io, double lowLimit, double highLimit, byte[] signature, string message) {
            return base.Channel.initialize(id, io, lowLimit, highLimit, signature, message);
        }
        
        public System.Threading.Tasks.Task<bool> initializeAsync(string id, string io, double lowLimit, double highLimit, byte[] signature, string message) {
            return base.Channel.initializeAsync(id, io, lowLimit, highLimit, signature, message);
        }
        
        public void ValueToAddres(string io, int number) {
            base.Channel.ValueToAddres(io, number);
        }
        
        public System.Threading.Tasks.Task ValueToAddresAsync(string io, int number) {
            return base.Channel.ValueToAddresAsync(io, number);
        }
    }
}
