//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManager.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmValue", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core")]
    [System.SerializableAttribute()]
    public partial class AlarmValue : ReportManager.ServiceReference1.Alarm {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TriggerValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TriggerValue {
            get {
                return this.TriggerValueField;
            }
            set {
                if ((this.TriggerValueField.Equals(value) != true)) {
                    this.TriggerValueField = value;
                    this.RaisePropertyChanged("TriggerValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alarm", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportManager.ServiceReference1.AlarmValue))]
    public partial class Alarm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagValue", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core")]
    [System.SerializableAttribute()]
    public partial class TagValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IReportManagerService")]
    public interface IReportManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsInTimeRange", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsInTimeRangeResponse")]
        ReportManager.ServiceReference1.AlarmValue[] GetAlarmsInTimeRange(System.DateTime from, System.DateTime to, string sortBy, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsInTimeRange", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsInTimeRangeResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference1.AlarmValue[]> GetAlarmsInTimeRangeAsync(System.DateTime from, System.DateTime to, string sortBy, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsByPriority", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsByPriorityResponse")]
        ReportManager.ServiceReference1.AlarmValue[] GetAlarmsByPriority(int prioritet, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsByPriority", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsByPriorityResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference1.AlarmValue[]> GetAlarmsByPriorityAsync(int prioritet, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagsInTimeRange", ReplyAction="http://tempuri.org/IReportManagerService/GetTagsInTimeRangeResponse")]
        ReportManager.ServiceReference1.TagValue[] GetTagsInTimeRange(System.DateTime from, System.DateTime to, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagsInTimeRange", ReplyAction="http://tempuri.org/IReportManagerService/GetTagsInTimeRangeResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetTagsInTimeRangeAsync(System.DateTime from, System.DateTime to, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetLastValuesAI", ReplyAction="http://tempuri.org/IReportManagerService/GetLastValuesAIResponse")]
        ReportManager.ServiceReference1.TagValue[] GetLastValuesAI(string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetLastValuesAI", ReplyAction="http://tempuri.org/IReportManagerService/GetLastValuesAIResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetLastValuesAIAsync(string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetLastValuesDI", ReplyAction="http://tempuri.org/IReportManagerService/GetLastValuesDIResponse")]
        ReportManager.ServiceReference1.TagValue[] GetLastValuesDI(string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetLastValuesDI", ReplyAction="http://tempuri.org/IReportManagerService/GetLastValuesDIResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetLastValuesDIAsync(string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagValuesByName", ReplyAction="http://tempuri.org/IReportManagerService/GetTagValuesByNameResponse")]
        ReportManager.ServiceReference1.TagValue[] GetTagValuesByName(string tagName, string sortType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagValuesByName", ReplyAction="http://tempuri.org/IReportManagerService/GetTagValuesByNameResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetTagValuesByNameAsync(string tagName, string sortType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportManagerServiceChannel : ReportManager.ServiceReference1.IReportManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportManagerServiceClient : System.ServiceModel.ClientBase<ReportManager.ServiceReference1.IReportManagerService>, ReportManager.ServiceReference1.IReportManagerService {
        
        public ReportManagerServiceClient() {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReportManager.ServiceReference1.AlarmValue[] GetAlarmsInTimeRange(System.DateTime from, System.DateTime to, string sortBy, string sortType) {
            return base.Channel.GetAlarmsInTimeRange(from, to, sortBy, sortType);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference1.AlarmValue[]> GetAlarmsInTimeRangeAsync(System.DateTime from, System.DateTime to, string sortBy, string sortType) {
            return base.Channel.GetAlarmsInTimeRangeAsync(from, to, sortBy, sortType);
        }
        
        public ReportManager.ServiceReference1.AlarmValue[] GetAlarmsByPriority(int prioritet, string sortType) {
            return base.Channel.GetAlarmsByPriority(prioritet, sortType);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference1.AlarmValue[]> GetAlarmsByPriorityAsync(int prioritet, string sortType) {
            return base.Channel.GetAlarmsByPriorityAsync(prioritet, sortType);
        }
        
        public ReportManager.ServiceReference1.TagValue[] GetTagsInTimeRange(System.DateTime from, System.DateTime to, string sortType) {
            return base.Channel.GetTagsInTimeRange(from, to, sortType);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetTagsInTimeRangeAsync(System.DateTime from, System.DateTime to, string sortType) {
            return base.Channel.GetTagsInTimeRangeAsync(from, to, sortType);
        }
        
        public ReportManager.ServiceReference1.TagValue[] GetLastValuesAI(string sortType) {
            return base.Channel.GetLastValuesAI(sortType);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetLastValuesAIAsync(string sortType) {
            return base.Channel.GetLastValuesAIAsync(sortType);
        }
        
        public ReportManager.ServiceReference1.TagValue[] GetLastValuesDI(string sortType) {
            return base.Channel.GetLastValuesDI(sortType);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetLastValuesDIAsync(string sortType) {
            return base.Channel.GetLastValuesDIAsync(sortType);
        }
        
        public ReportManager.ServiceReference1.TagValue[] GetTagValuesByName(string tagName, string sortType) {
            return base.Channel.GetTagValuesByName(tagName, sortType);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference1.TagValue[]> GetTagValuesByNameAsync(string tagName, string sortType) {
            return base.Channel.GetTagValuesByNameAsync(tagName, sortType);
        }
    }
}
